/*
 * Created on 2004-6-13
 *
 * To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package WebServlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * @author haoyulong
 *
 * To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
public class AdminTemperatureServlet extends HttpServlet {
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
		response.setContentType("text/html;charset=gb2312");
		PrintWriter out = response.getWriter();
		String Temperature=(String)getServletConfig().getServletContext().getAttribute("Temperature");
        if(Temperature==null){
        	Temperature=(String)getServletConfig().getInitParameter("Temperature");//�ӳ�ʼ����������
        	getServletConfig().getServletContext().setAttribute("Temperature",Temperature);//����Ӧ��������
        }
        out.println("<HTML><HEAD><TITLE>���¸��� "
	                + "</TITLE></HEAD>");
	    out.println("<BODY><TABLE border=\"0\" width=\"100%\"><tr>");
	    out.println("<td align=\"left\" valign=\"bottom\">");
	    out.println("<H1>��ǰ����</H1></td></tr></TABLE>");
	    
	    out.print("<FORM ACTION=\"");
	    out.println(response.encodeURL("AdminTemperatureServlet"));
	    out.println("\" METHOD=\"POST\">");
	    out.println("��ǰ���£����϶ȣ�");
	    out.println("<INPUT TYPE=\"text\" NAME=\"temperature\" "
                + "VALUE="+Temperature+">");
	    out.println("<INPUT TYPE=\"Submit\" NAME=\"btn_submit\" "
	                + "VALUE=\"����\">");
	    out.println("</FORM></BODY></HTML>");
	}
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
		
		response.setContentType("text/html;charset=gb2312");
		PrintWriter out = response.getWriter();
		String Temperature=request.getParameter("temperature");
       //		�����º��������Ϣ����������       
		getServletConfig().getServletContext().setAttribute("Temperature",Temperature);
        out.println("<HTML><HEAD><TITLE>���¸��� "
	                + "</TITLE></HEAD>");
	    out.println("<BODY>");
	    out.println("��ǰ���£�"+Temperature+"���϶�");
	   
	    out.println("</BODY></HTML>");
		
	}

}
