package WebServlet.ServletDemo;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
/**
 * Created by KAI on 2017/11/23.
 */
@WebServlet(name = "HitCounter",urlPatterns="/hitcounter")



/**
 * @author haoyulong
 *
 * To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
public class HitCounter extends HttpServlet {
    static  final  String COUNTER_KEY = "Counter";
    protected void doGet(HttpServletRequest request,
                         HttpServletResponse response) throws ServletException, IOException {
        //TODO Method stub generated by Lomboz
//		获取会话对象
        HttpSession session = request.getSession(true);

        response.encodeURL(request.getRequestURI());
        response.setContentType("text/html;charset=gb2312");
// Get the PrintWriter to write the response
        java.io.PrintWriter out = response.getWriter();
// 从会话中获取属性
        int count = 1;
        Integer i = (Integer) session.getAttribute(COUNTER_KEY);
// If a previous count exists, set it
        if (i != null) {
            count = i.intValue() + 1;
        }
// 将属性信息存入会话
        session.setAttribute(COUNTER_KEY, new Integer(count));
//
        Date lastAccessed = new Date(session.getLastAccessedTime( ));
        Date sessionCreated=new Date(session.getCreationTime());
        DateFormat formatter =
                DateFormat.getDateTimeInstance(DateFormat.MEDIUM,
                        DateFormat.MEDIUM);

//
// Print a standard header
        out.println("<html>");
        out.println("<head>");
        out.println("<title>会话计数器</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("你的会话ID: <b>" +session.getId()+ "<br>");
        out.println("会话创建时间："+formatter.format(sessionCreated) + "<br>");
        out.println("会话上次访问时间："+formatter.format(lastAccessed) + "<br>");
        out.println("</b> 会话期间你对页面发起 <b>" +
                count +	"</b> 次请求");
        out.println("<form method=GET action=\"" +
                request.getRequestURI() + "\">");
        out.println("<input type=submit " +
                "value=\"再次点击...\">");
        out.println("</form>");
        // Wrap up
        out.println("</body>");
        out.println("</html>");
        out.flush();

    }

}

